### ISSUE TITLE
Code quality is really bad

### ISSUE THREAD

**Issue by matthofmarch** [WirthLukas/Bloccly#1]
This is just a test
This is just a test

**Comment by WirthLukas** [comment]
Thank you for your information. We are working on it

**Comment by matthofmarch** [comment]
Why is there still no fix for it?! The support is horrible, it has been nearly 3 days and you haven't finished the project! (╯°□°）╯︵ ┻━┻

**Comment by WirthLukas** [comment]
We are still working hard in order to finish the project.

**Comment by WirthLukas** [comment]
no!
